services:
  parse:
    container_name: parse-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    depends_on:
      - mongodb
    restart: always
    environment:
      DATABASE_URI: mongodb://root:example@mongodb:27017/parse?authSource=admin
  mongodb:
    container_name: parse-db
    image: mongo
    restart: always
    volumes:
      - ./db-data:/data/db
    environment:
      MONGO_INITOR_DATABASE: parse
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: parse-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
